### ISSUE TITLE
Guide: Message connection - adding code in creating messages locks up browser

### ISSUE THREAD

**Issue by BigAB** [bitovi/donejs#5]
I was trying to go through the guide using node@0.10.36 and npm@2.13.5, and I got to the [Message Connection](http://donejs.com/Guide.html#section=section_Messageconnection) section, and it seems to lock up my browser. 

It seems like it may be because of these lines in src/messages/messages.stache `{($value)}="message" ($enter)=“send”`
as when I remove them, it seems to work okay… though obviously it actually stops working as intended.

Server side rendering does not seem to complete in this case either.
<img width="400" alt="screen shot 2015-10-05 at 3 42 56 pm" src="https://cloud.githubusercontent.com/assets/76821/10294609/b5eb651a-6b78-11e5-8ee3-8f59d91a3d80.png">

**Comment by justinbmeyer** [comment]
Are you sure you have latest?

**Comment by BigAB** [comment]
I have what I got by doing `npm install -g donejs`.

Not sure why that isn't giving me @latest

**Comment by justinbmeyer** [comment]
you have to specify ... it gives you the latest release that isn't a beta/pre release.  I'm going to close.  Reopen if you encounter bugs with latest.

> npm install -g donejs@0.5.0-pre.13
